### ISSUE TITLE
Ubuntu 22.04 LTS系统下运行beta0.6.3仍然一片白

### ISSUE THREAD

**Issue by ErrorDreemurr** [ResetPower/Epherome#90]
是我的打开方式不对吗

**Comment by ResetPower** [comment]
请提供报错信息。
使用快捷键 Ctrl+Shift+I 打开 Developer Tools，点击 Console，如果发现了红底的报错信息请截图发上来。

**Comment by ErrorDreemurr** [comment]
node:electron/js2c/renderer_init:73 Unable to load preload script: /opt/Epherome/resources/app.asar/dist/preload.js
(anonymous) @ node:electron/js2c/renderer_init:73
node:electron/js2c/renderer_init:73 Error: libssl.so.1.1: æ æ³æå¼å±äº«å¯¹è±¡æä»¶: æ²¡æé£ä¸ªæä»¶æç®å½
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at i._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/Epherome/resources/app.asar/dist/preload.js:1:172)
(anonymous) @ node:electron/js2c/renderer_init:73
app.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'findJavas')
    at 1356 (app.js:2:12234782)
    at a (app.js:2:12466963)
    at 5635 (app.js:2:12259950)
    at a (app.js:2:12466963)
    at 4916 (app.js:2:12334176)
    at a (app.js:2:12466963)
    at 3874 (app.js:2:12316066)
    at a (app.js:2:12466963)
    at 1945 (app.js:2:12286507)
    at a (app.js:2:12466963)

貌似出现了乱码？

**Comment by ResetPower** [comment]
我装个ubuntu虚拟机看看吧😂

**Comment by ResetPower** [comment]
## 原因分析
大概是某个 Rust 库引用了 libssl 中的内容，然后 Ubuntu 22.04 刚好没有这玩意
## 解决方法
安装这个东西：https://packages.ubuntu.com/bionic/amd64/libssl1.1/download
