### ISSUE TITLE
运行 Forge 和 Quilt 直接报废

### ISSUE THREAD

**Issue by ResetPower** [ResetPower/Epherome#93]
Quilt:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/49084517/189570647-0aace655-e9f5-4ef1-93bf-87060b4a8e92.png">
Forge:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/49084517/189570721-335564a1-3712-432e-b249-d852f7721d78.png">
```
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-exports

WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-opens WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-opens

Exception in thread "main"

java.lang.ExceptionInInitializerError

at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:115) at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:105) at cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:84) at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70) at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:66) at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58) at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50) at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:84)

Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field static final java.lang.invoke.MethodHandles$Lookup java.lang.invoke.MethodHandles$Lookup.IMPL_LOOKUP accessible: module java.base does not "opens java.lang.invoke" to unnamed module @4926097b at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)

at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) at java.base/java.lang.reflect.Field.setAccessible(Field.java:172) at cpw.mods.niofs.union.UnionFileSystem.<clinit>(UnionFileSystem.java:45) ... 8 more
```

**Comment by ResetPower** [comment]
看到这个 issue 的人，我建议你们转到 HMCL 🤔
