### ISSUE TITLE
Ubuntu22.04.1无法使用

### ISSUE THREAD

**Issue by bingxin666** [ResetPower/Epherome#99]
如题，打开就一片空白

**Comment by ResetPower** [comment]
请提供更多信息
例如按下 Ctrl+Shift+I （在 macOS 下则是 Command+Option+I）后弹出的页面中「Console」一栏中的报错信息。

**Comment by CreeperLKF** [comment]
> 请提供更多信息 例如按下 Ctrl+Shift+I （在 macOS 下则是 Command+Option+I）后弹出的页面中「Console」一栏中的报错信息。
在Ctrl+Shift+I中Console的报错信息是：
```
node:electron/js2c/renderer_init:73 Unable to load preload script: /opt/Epherome/resources/app.asar/dist/preload.js
(anonymous) @ node:electron/js2c/renderer_init:73
node:electron/js2c/renderer_init:73 Error: libssl.so.1.1: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at i._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/Epherome/resources/app.asar/dist/preload.js:1:172)
(anonymous) @ node:electron/js2c/renderer_init:73
app.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'findJavas')
    at 1356 (app.js:2:12234878)
    at a (app.js:2:12467790)
    at 5635 (app.js:2:12260162)
    at a (app.js:2:12467790)
    at 4916 (app.js:2:12334461)
    at a (app.js:2:12467790)
    at 3874 (app.js:2:12316351)
    at a (app.js:2:12467790)
    at 1945 (app.js:2:12286792)
    at a (app.js:2:12467790)
```
在用于启动启动器的终端的信息是：
```
[2023-01-06T22:14:14.494] [INFO] main - *** Epherome 0.6.5 ***
[2023-01-06T22:14:14.495] [INFO] main - Epherome  Copyright (C) 2021  ResetPower
[2023-01-06T22:14:14.495] [INFO] main - Epherome is running on production mode
[2023-01-06T22:14:14.495] [INFO] main - Operating System: linux x64 5.15.0-56-generic
[2023-01-06T22:14:14.495] [INFO] main - Node.js Version: 16.15.0
[2023-01-06T22:14:14.495] [INFO] main - V8 Version: 10.4.132.23-electron.0
[2023-01-06T22:14:14.495] [INFO] main - Chrome Version: 104.0.5112.114
[2023-01-06T22:14:14.495] [INFO] main - Electron Version: 20.1.4
[2023-01-06T22:14:14.495] [INFO] main - Epherome Directory: '/home/xxx/.config/epherome'
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[283553:0106/221418.632111:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[283553:0106/221423.715173:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[283553:0106/221438.803574:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

**Comment by ResetPower** [comment]
已经推断出原因
这个原因造成了很大一部分机器无法正常使用
将会在0.7移除

**Comment by ResetPower** [comment]
The problem has been solved in the latest commit.
